// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NurseProblem.Datenbank;

#nullable disable

namespace NurseProblem.Migrations
{
    [DbContext(typeof(ScheduleDbContext))]
    [Migration("20251223100935_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("NurseProblem.Models.DbModelle.DayEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Days");
                });

            modelBuilder.Entity("NurseProblem.Models.DbModelle.NurseEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmploymentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("UnavailableDays")
                        .HasColumnType("INTEGER");

                    b.Property<double>("WorkingHours")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Nurses", null, t =>
                        {
                            t.HasCheckConstraint("CK_Nurse_WorkingHours", "WorkingHours > 0");
                        });
                });

            modelBuilder.Entity("NurseProblem.Models.DbModelle.ShiftSlotEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DayEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NurseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NurseName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Shift")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlotNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DayEntityId");

                    b.ToTable("ShiftSlots");
                });

            modelBuilder.Entity("NurseProblem.Models.DbModelle.ShiftSlotEntity", b =>
                {
                    b.HasOne("NurseProblem.Models.DbModelle.DayEntity", "Day")
                        .WithMany("ShiftSlots")
                        .HasForeignKey("DayEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Day");
                });

            modelBuilder.Entity("NurseProblem.Models.DbModelle.DayEntity", b =>
                {
                    b.Navigation("ShiftSlots");
                });
#pragma warning restore 612, 618
        }
    }
}
